### ISSUE TITLE
config files for the portable version

### ISSUE THREAD

**Issue by YZgitter** [terreng/simple-web-server#285]
The current "portable" version stores the config files in the same location as the installed version.
For an app to be actually portable, the config should be in the same folder as the executable (in a subfolder). Is there a way to make them go there and not place the files elsewhere? If not, please consider this a feature request.

**Comment by Aynyuh** [comment]
I also needed the same feature that @YZgitter requested, so I implemented it in the fork in a separate branch [feature/portable-config](https://github.com/Aynyuh/simple-web-server/tree/feature/portable-config).

The logic behind this improvement is very simple: if SWS finds a `config.json` file next to the executable, it uses that file instead of loading the configuration from one of the [default locations](https://simplewebserver.org/docs/config%20file.html) (such as `%appdata%\Simple Web Server\config.json`, etc.). In other words, the bundled `config.json` takes precedence over the user-wide configuration file - simply copy your `config.json` to the SWS folder.

You can check the source and build Simple Web Server on your own using `feature/portable-config` branch or download artifacts from the build action here:
https://github.com/Aynyuh/simple-web-server/actions/workflows/build.yml

**Comment by terreng** [comment]
@Aynyuh Thanks for sharing this code! I'm still not sure what I want to do with this issue, but I think it would be a good solution if the app attempted to load from either place. And maybe on first launch it could let you pick where to save the config.
